import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import { getConfig, SvConfig } from './config';
import { resolveFileList } from './filelist';
import * as logger from './logger';

// Generates the slang-server configuration from the extension's fileLists /
// includeDirs settings. The filelist paths are resolved by the extension itself
// (honouring each entry's `base`), then written as a cwd-relative command file
// that slang-server references from `.slang/server.json` via `-f`. Existing keys
// and flags are preserved; the generated `-f` reference is refreshed in place.
//
// The command file lists the filelist's files *as-is* (including `.svh` package
// headers) and the include directories; the server follows `` `include `` itself,
// exactly like the simulator would. The extension does not expand the include
// closure into separate top-level sources, which would recompile them outside
// their package scope.
//
// Only slang-server is targeted. The generated `flags` reference is
// `-f .slang/systemverilog.f`, which slang resolves against the server's working
// directory (the workspace root).
const CONFIG_REL = ['.slang', 'server.json'];
const FLAG_REL = ['.slang', 'systemverilog.f'];
const FLAG_REF = '-f .slang/systemverilog.f';
const FLAG_HEADER = '// Generated by vscode-systemverilog from systemverilog.fileLists / includeDirs. Do not edit.';

function readTextSync(p: string): string | null {
  try {
    return fs.readFileSync(p, 'utf8');
  } catch {
    return null;
  }
}

function resolveWorkspacePath(p: string, root: string): string {
  return path.isAbsolute(p) ? p : path.join(root, p);
}

// Prefer a path relative to the workspace root (portable, and how `-f` resolves
// inside the generated command file); fall back to an absolute path for files
// outside the workspace.
function toCommandPath(abs: string, root: string): string {
  const rel = path.relative(root, abs);
  const base =
    rel && !rel.startsWith('..') && !path.isAbsolute(rel) ? rel : abs;
  return base.split(path.sep).join('/');
}

interface SyncResult {
  fileCount: number;
  incdirCount: number;
  configPath: string;
  flagPath: string;
}

// Build the resolved command file body from the current settings.
function buildFlagFile(cfg: SvConfig, root: string): { body: string; files: number; incdirs: number } {
  const globalInc = cfg.includeDirs.map((d) => resolveWorkspacePath(d, root));
  const entries = cfg.fileLists.filter((l) => l.file && l.base);
  const files = new Set<string>();
  const incdirs = new Set<string>(globalInc);

  for (const entry of entries) {
    const listPath = resolveWorkspacePath(entry.file, root);
    const basePath = resolveWorkspacePath(entry.base, root);
    let resolved;
    try {
      resolved = resolveFileList(listPath, basePath, readTextSync);
    } catch (e) {
      logger.warn(`slang sync: fileList ${entry.file}: ${e}`);
      continue;
    }
    incdirs.add(basePath);
    for (const d of resolved.incdirs) {
      incdirs.add(d);
    }
    for (const f of resolved.files) {
      files.add(path.resolve(f));
    }
  }

  const lines: string[] = [FLAG_HEADER];
  // Preserve the filelist order: it is a compile order (significant with
  // `--single-unit`), so entries must not be sorted.
  for (const dir of incdirs) {
    lines.push('+incdir+' + toCommandPath(dir, root));
  }
  for (const file of files) {
    lines.push(toCommandPath(file, root));
  }
  return { body: lines.join('\n') + '\n', files: files.size, incdirs: incdirs.size };
}

function readConfigJson(cfgPath: string): Record<string, unknown> | null {
  const text = readTextSync(cfgPath);
  if (text === null || text.trim() === '') {
    return {};
  }
  try {
    const parsed = JSON.parse(text);
    if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
      return parsed as Record<string, unknown>;
    }
    logger.warn('slang sync: .slang/server.json is not a JSON object, leaving it untouched');
    return null;
  } catch (e) {
    logger.warn(`slang sync: .slang/server.json is invalid JSON, leaving it untouched (${e})`);
    return null;
  }
}

function stripFlagRef(flags: string): string {
  return flags
    .replace(/(?:^|\s)-[fF]\s+"?\.slang[\\/]systemverilog\.f"?/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function writeIfChanged(filePath: string, content: string): void {
  if (readTextSync(filePath) === content) {
    return;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
}

// Generate / update the slang-server config. No-op unless the language server is
// enabled and `systemverilog.languageServer.syncConfig` is on.
export async function syncSlangServerConfig(): Promise<void> {
  const cfg = getConfig();
  if (!cfg.languageServerEnabled || !cfg.languageServerSyncConfig) {
    return;
  }
  const folder = vscode.workspace.workspaceFolders?.[0];
  if (!folder) {
    logger.debug('slang sync: no workspace folder, skipping');
    return;
  }
  const root = folder.uri.fsPath;
  const cfgPath = path.join(root, ...CONFIG_REL);
  const flagPath = path.join(root, ...FLAG_REL);

  const json = readConfigJson(cfgPath);
  if (json === null) {
    return;
  }

  const { body, files, incdirs } = buildFlagFile(cfg, root);
  const hasContent = files > 0 || incdirs > 0;

  if (!hasContent) {
    // Nothing to sync: drop the generated reference (and flag file) so slang does
    // not point at a stale or empty command file.
    if (fs.existsSync(flagPath)) {
      fs.rmSync(flagPath);
    }
    const flags = typeof json.flags === 'string' ? json.flags : '';
    const stripped = stripFlagRef(flags);
    if (stripped !== flags.trim()) {
      if (stripped) {
        json.flags = stripped;
      } else {
        delete json.flags;
      }
      writeIfChanged(cfgPath, JSON.stringify(json, null, 2) + '\n');
      logger.info('slang sync: removed generated flags (no fileLists/includeDirs)');
    }
    return;
  }

  const flags = typeof json.flags === 'string' ? json.flags : '';
  const stripped = stripFlagRef(flags);
  json.flags = (stripped ? stripped + ' ' : '') + FLAG_REF;

  writeIfChanged(flagPath, body);
  writeIfChanged(cfgPath, JSON.stringify(json, null, 2) + '\n');

  const result: SyncResult = { fileCount: files, incdirCount: incdirs, configPath: cfgPath, flagPath };
  logger.info(
    `slang sync: ${result.fileCount} file(s), ${result.incdirCount} incdir(s) -> ${vscode.workspace.asRelativePath(cfgPath)}`
  );
}
